<table style="float:left">
    <tr>
        <td>
            <img src="images/emlyon.png" style="height:60px; float:left; padding-right:10px; margin-top:5px" />
        </td>
        <td style="padding-bottom:10px;">
            <h1 style="border-bottom: 1px solid #eeeeee;"> AI Booster Week 01 - Python for Data Science </h1>
            <span style="display:inline-block; margin-top:-15px;">
            <a href="https://masters.em-lyon.com/fr/msc-in-data-science-artificial-intelligence-strategy">[Emlyon]</a> MSc in Data Science & Artificial Intelligence Strategy (DSAIS)    
            <br/>
            Sep 2024, Paris | © Vincent SCHOOTS
            </span>
        </td>
    </tr>
</table>

### Exercise 1: Convert two lists into a dictionary

Below are the two lists. Write a Python program to convert them into a dictionary in a way that item from list1 is the key and item from list2 is the value

Use the zip() function. This function takes two or more iterables (like list, dict, string), aggregates them in a tuple, and returns it.

Expected Output:
`{'Ten': 10, 'Twenty': 20, 'Thirty': 30}`

In [2]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]

In [8]:
# your_code_here

new_dict = {keys: values for keys,
            values in zip(keys, values)}
new_dict

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

### Exercise 2:
__Calculate sum of all numbers from 1 to a given number__

Write a Python program to accept a number from a user and calculate the sum of all numbers from 1 to a given number

For example, if the user entered 10, the output should be 55 (1+2+3+4+5+6+7+8+9+10)

Expected Output:

`Enter number 10
Sum is:  55`

In [15]:
# Get input
def summin(n):
    sum=0
    for i in range(0,n+1):
        sum=sum+i
    print(f"Sum is: {sum}")


# Pass range of numbers to sum() function
n=int(input("enter number: "))
summin(n)


enter number: 10
Sum is: 55


### Exercise 3: 
__Write a function called mul_table that takes as input a number and prints the multiplication table of that number__

Then run it.

See if you can use the .format() method

Expected output when input = 9:

`9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90`

In [17]:
# your_code_here

def mul_table(n):
    for i in range(1,n+2):
        print(f'{9} * {i} = {9*i} ')
    
mul_table(9)



9 * 1 = 9 
9 * 2 = 18 
9 * 3 = 27 
9 * 4 = 36 
9 * 5 = 45 
9 * 6 = 54 
9 * 7 = 63 
9 * 8 = 72 
9 * 9 = 81 
9 * 10 = 90 


### Exercise 4: 
__Arrange string characters such that uppercase letters should come first__

Decode the secret!
The given string contains a combination of the lower and upper case letters. Write a program to arrange the characters of a string so that all uppercase letters should come first.

Hint: a straightforward solution uses a for loop, an if/else, and several string methods (methods are the thing you call by appending a dot to the name of the python object, for example:

`last_name = "Dupont"
last_name.upper()`
returns
`DUPONT`

In [5]:
last_name = "Dupont"
last_name.upper()

'DUPONT'

In [20]:
secret = "yILtOhVonEP"

In [7]:
# your_code_here
          

print('Scrambled String:', secret)
print('Result:', sorted_str)

Scrambled String: yILtOhVonEP
Result: ILOVEPython


In [23]:
def update_strings(n):
    upper=[]
    lower=[]
    for i in n:
        if i.isupper():
            upper.append(i)
        elif i.islower():
            lower.append(i)
    fullstring=upper+lower
    
    return "".join(fullstring)

update_strings(secret)

'ILOVEPython'

## Import Numpy as np

In [8]:
#your_code_here

### Exercise 5:
Following is a provided numPy array. Return array of items by taking the second column from all rows. Print it.

Expected output:

`Printing array of items in the third column from all rows:
[22 55 88]`

In [25]:
import numpy as np
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 



In [31]:
sampleArray

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [33]:
lista=[]
for i in range(0,3):
    lista.append(sampleArray[i][1])
lista

[22, 55, 88]

### Exercise 6a:
__Create a 4X2 integer array and Print its attributes__

You can decide which integers, below is just an example.
Print the following Attributes:

    The shape of an array.
    Array dimensions.
    The Length of each element of the array in bytes.

#### Expected Output:
```
Printing Array

[[64392 31655]
 [32579     0]
 [49248   462]
 [    0     0]]

Printing NumPy array Attributes

Array shape is  (4, 2)
Array dimensions are  2
Array sum is  178336
```

Tip: you can tell the print command to include an "enter" into the output by including \n

See if you can make use of the f-string functionality from day 1

*Remember to comment your code!*

In [42]:
# Building the array
import numpy
def make_42array():
    arr=numpy.empty(shape=(4, 2), dtype='object')
    for i in range(0,4):
        for j in range(0,2):
            n=int(input(f"enter number for array no [{i}] [{j}] :"))
            arr[i][j]=n
    print(arr)
    print("Attributes of array")
    print(f"Array shape is {arr.shape}")
    print(f"Array dimensions is {arr.ndim}")
    print(f"Array sum is {arr.sum()}")
    

make_42array()

enter number for array no [0] [0] :88
enter number for array no [0] [1] :55
enter number for array no [1] [0] :11
enter number for array no [1] [1] :6
enter number for array no [2] [0] :88
enter number for array no [2] [1] :2
enter number for array no [3] [0] :66
enter number for array no [3] [1] :77
[[88 55]
 [11 6]
 [88 2]
 [66 77]]
Attributes of array
Array shape is (4, 2)
Array dimensions is 2
Array sum is 393


In [11]:
# Creating the output

Printing Array

[[64392 31655]
 [32579     0]
 [49248   462]
 [    0     0]] 

Printing NumPy array Attributes

Array shape is  (4, 2)
Array dimensions are  2
Array sum is  178336


### Exercise 6b:
__make a function that does the same__

The function should be able to take *any* 2-dimensional Numpy array of integers

Than use the package called random to make a new 2-dimensional array as above and run your function on it. Make it a different shape!

In [60]:
# your_code_here
def make_any2darray(m,n):
    print(f"the m is {m}, the n is {n}")
    arr=numpy.empty(shape=(m, n), dtype='object')
    for i in range(0,n):
        for j in range(0,m):
            n=int(input(f"enter number for array no [{i}] [{j}] :"))
            arr[i][j]=n
    print(arr)
    print("Attributes of array")
    print(f"Array shape is {arr.shape}")
    print(f"Array dimensions is {arr.ndim}")
    print(f"Array sum is {arr.sum()}")
    



In [61]:
# import random
import random
m=random.randint(1,5)
n=random.randint(1,5)



# make a new array
make_any2darray(m,n)



the m is 4, the n is 4
enter number for array no [0] [0] :88
enter number for array no [0] [1] :566
enter number for array no [0] [2] :211
enter number for array no [0] [3] :666
enter number for array no [1] [0] :777
enter number for array no [1] [1] :55
enter number for array no [1] [2] :22
enter number for array no [1] [3] :22
enter number for array no [2] [0] :666
enter number for array no [2] [1] :77
enter number for array no [2] [2] :999
enter number for array no [2] [3] :5
enter number for array no [3] [0] :66
enter number for array no [3] [1] :22
enter number for array no [3] [2] :77
enter number for array no [3] [3] :33
[[88 566 211 666]
 [777 55 22 22]
 [666 77 999 5]
 [66 22 77 33]]
Attributes of array
Array shape is (4, 4)
Array dimensions is 2
Array sum is 4352


In [14]:
# apply the function on the array


Printing Array

[[162 200 199  69  84  56  53 102  25 175   1 124  58  31 120   3]
 [154 133 152 170 115 152  14 199  42 193  77  13  93  32  28  34]] 

Printing NumPy array Attributes

Array shape is  (2, 16)
Array dimensions are  2
Array sum is  3063


### Exercise 6c: 
__use reshape to mold your latest 2-d array into a 3-dimensional array__

Does it work? If not, what could be the problem? (hint: you may need to drop or add elements to arrive at a suitable number that can fit the new shape)

In [65]:
#Reshape the array
array_3d = sampleArray.reshape((1, 3, 3))
array_3d

array([[[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]])

### Exercise 6d: 
__see if your function also works for 3-dimensional arrays.__
If it doesn't, why not? See if you can fix it.

In [66]:
# Run the function on the latest array
array_3d2 = array_3d.reshape((3, 3, 1))
array_3d2

array([[[11],
        [22],
        [33]],

       [[44],
        [55],
        [66]],

       [[77],
        [88],
        [99]]])

### Exercise 7:
__Following is a new provided numPy array. Return array of odd (impair) rows and even (pair) columns. Print it__

In [67]:
sampleArray = np.array([[3 ,9, 9, 12], [16 ,18, 231, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 58], [51 ,54, 57, 61]]) 
print("Input Array:")
print(sampleArray)

print("\nPrinting array of odd rows and even columns:")


Input Array:
[[  3   9   9  12]
 [ 16  18 231  24]
 [ 27  30  33  36]
 [ 39  42  45  58]
 [ 51  54  57  61]]

Printing array of odd rows and even columns:


[[ 9 12]
 [30 36]
 [54 61]]

In [73]:
array=[]
for i in range(0,sampleArray.shape[0]):
    for j in range(0,sampleArray.shape[1]):
        if (i%2==0) and (j%2!=0):
            array.append(sampleArray[i][j])
print(array)
res = np.array(array)
array_oddeven = res.reshape(( 3, 2))
array_oddeven

[9, 12, 30, 36, 54, 61]


array([[ 9, 12],
       [30, 36],
       [54, 61]])

### Exercise 8:
__Iterate two lists simultaneously__

Given a two Python list. Write a program to iterate both lists simultaneously and display items from list1 in original order and items from list2 in reverse order.

Tip: you can return a list in reverse with `[::-1]` (can you understand why?)

Expected output:

`10 400
20 300
30 200
40 100`

In [84]:
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]

In [19]:
# your_code_here


10 400
20 300
30 200
40 100


In [94]:
for i in range(0,4):
    print(f"{list1[i]} {list2[-(i+1)]}")

10 400
20 300
30 200
40 100


### Exercise 9:
__Replace list’s item with new value if found__

You are given a Python list. Write a program to find value 20 in the list, and if it is present, replace it with 200. Only update the first occurrence of the item.

In [106]:
list1 = [5, 10, 15, 20, 25, 50, 20]

# your_code_here


In [107]:
for i in range(len(list1)):
    if list1[i]==20:
        list1[i]=200
        break
        
list1

[5, 10, 15, 200, 25, 50, 20]