<div>
    <span>
        <h1 style="padding-bottom:5px;"> AI Booster Week 01 - Python for Data Science </h1>
        <a href="https://masters.em-lyon.com/fr/msc-in-data-science-artificial-intelligence-strategy">[Emlyon]</a> MSc in Data Science & Artificial Intelligence Strategy (DSAIS) <br/>
         Paris | Vincent SCHOOTS
    </span>
</div>

### Exercise 1: Convert two lists into a dictionary

Below are the two lists. Write a Python program to convert them into a dictionary in a way that item from list1 is the key and item from list2 is the value

Use the zip() function. This function takes two or more iterables (like list, dict, string), aggregates them in a tuple, and returns it.

Expected Output:
`{'Ten': 10, 'Twenty': 20, 'Thirty': 30}`

In [4]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]

In [2]:
# your_code_here
res_dict = dict(zip(keys, values))
print(res_dict)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}


In [3]:

dict[6]

TypeError: 'type' object is not subscriptable

### Exercise 2:
__Calculate sum of all numbers from 1 to a given number__

Write a Python program to accept a number from a user and calculate the sum of all numbers from 1 to a given number

For example, if the user entered 10, the output should be 55 (1+2+3+4+5+6+7+8+9+10)

Expected Output:

`Enter number 10
Sum is:  55`

In [3]:
# Get input
n = int(input("Enter number "))

# Pass range of numbers to sum() function
x = sum(range(1, n + 1))
print('Sum is:', x)

Enter number 13
Sum is: 91


### Exercise 3: 
__Write a function called mul_table that takes as input a number and prints the multiplication table of that number__

Then run it.

See if you can use the .format() method

Expected output when input = 9:

`9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90`

In [4]:
def mul_table(n):
    for i in range(1, 11):
        print("{multiplier} * {multiplicand} = {multiplicantion}".format(
            multiplier=n, multiplicand=i, multiplicantion=n * i))

mul_table(9)

9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90


### Exercise 4: 
__Arrange string characters such that uppercase letters should come first__

Decode the secret!
The given string contains a combination of the lower and upper case letters. Write a program to arrange the characters of a string so that all lowercase letters should come first.

Hint: a straightforward solution uses a for loop, an if/else, and several string methods (methods are the thing you call by appending a dot to the name of the python object, for example:

`last_name = "Dupont"
last_name.upper()`
returns
`DUPONT`

In [5]:
last_name = "Dupont"
last_name.upper()

'DUPONT'

In [6]:
secret = "yILtOhVonEP"

In [7]:
# your_code_here

print('Scrambled String:', secret)
lower = []
upper = []
for char in secret:
    if char.isupper():
        # add lowercase characters to lower list
        upper.append(char)
    else:
        # add uppercase characters to lower list
        lower.append(char)

# Join both list
sorted_str = ''.join(upper + lower)
print('Result:', sorted_str)

Scrambled String: yILtOhVonEP
Result: ILOVEPython


### Import Numpy as np

In [8]:
import numpy as np

### Exercise 5:
Following is a provided numPy array. Return array of items by taking the second column from all rows. Print it.

Expected output:

`Printing array of items in the third column from all rows:
[22 55 88]`

In [9]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Input Array:")
print(sampleArray)

print("\nPrinting array of items in the third column from all rows:")
newArray = sampleArray[:,1]
print(newArray)


Input Array:
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Printing array of items in the third column from all rows:
[22 55 88]


### Exercise 6a:
__Create a 4X2 integer array and Print its attributes__

You can decide which integers, below is just an example.
Print the following Attributes:

    The shape of an array.
    Array dimensions.
    The Length of each element of the array in bytes.

#### Expected Output:
```
Printing Array

[[64392 31655]
 [32579     0]
 [49248   462]
 [    0     0]]

Printing NumPy array Attributes

Array shape is  (4, 2)
Array dimensions are  2
Array sum is  178336
```

Tip: you can tell the print command to include an "enter" into the output by including \n

See if you can make use of the f-string functionality from day 1

*Remember to comment your code!*

In [10]:
# Building the array
to_array = [[64392, 31655],
 [32579,     0],
 [49248,   462],
 [    0,     0]]

array = np.array(to_array)


In [11]:
# Collecting the demanded attributes
arr_shp = array.shape
arr_dim = array.ndim
arr_sum = array.sum()

# Printing everything
print("Printing Array\n")
print(array, "\n")
print("Printing NumPy array Attributes\n")
print(f"Array shape is  {arr_shp}")
print(f"Array dimensions are  {arr_dim}")
print(f"Array sum is  {arr_sum}")

Printing Array

[[64392 31655]
 [32579     0]
 [49248   462]
 [    0     0]] 

Printing NumPy array Attributes

Array shape is  (4, 2)
Array dimensions are  2
Array sum is  178336


### Exercise 6b:
__make a function that does the same__

The function should be able to take *any* 2-dimensional Numpy array of integers

Than use the package called random to make a new 2-dimensional array as above and run your function on it. Make it a different shape!

In [12]:
def print_array_attributes(array):
    # Collecting the demanded attributes
    arr_shp = array.shape
    arr_dim = array.ndim
    arr_sum = array.sum()

    # Printing everything
    print("Printing Array\n")
    print(array, "\n")
    print("Printing NumPy array Attributes\n")
    print(f"Array shape is  {arr_shp}")
    print(f"Array dimensions are  {arr_dim}")
    print(f"Array sum is  {arr_sum}")

In [13]:
# import random
import random 

# make a new array
elements = [random.randint(0, 200) for _ in range(32)]
new_arr = np.array(elements)
new_arr = new_arr.reshape(2, -1)

In [14]:
# apply the function on the array
print_array_attributes(new_arr)

Printing Array

[[162 200 199  69  84  56  53 102  25 175   1 124  58  31 120   3]
 [154 133 152 170 115 152  14 199  42 193  77  13  93  32  28  34]] 

Printing NumPy array Attributes

Array shape is  (2, 16)
Array dimensions are  2
Array sum is  3063


### Exercise 6c: 
__use reshape to mold your latest 2-d array into a 3-dimensional array__

Does it work? If not, what could be the problem? (hint: you may need to drop or add elements to arrive at a suitable number that can fit the new shape)

In [15]:
#Reshape the array
newest_arr = np.array(elements).reshape(2,2,-1)

### Exercise 6d: 
__see if your function also works for 3-dimensional arrays.__
If it doesn't, why not? See if you can fix it.

In [16]:
# Run the function on the latest array
print_array_attributes(newest_arr)

Printing Array

[[[162 200 199  69  84  56  53 102]
  [ 25 175   1 124  58  31 120   3]]

 [[154 133 152 170 115 152  14 199]
  [ 42 193  77  13  93  32  28  34]]] 

Printing NumPy array Attributes

Array shape is  (2, 2, 8)
Array dimensions are  3
Array sum is  3063


### Exercise 7:
__Following is a new provided numPy array. Return array of odd (impair) rows and even (pair) columns. Print it__

In [17]:
sampleArray = np.array([[3 ,9, 9, 12], [16 ,18, 231, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 58], [51 ,54, 57, 61]]) 
print("Input Array:")
print(sampleArray)

print("\nPrinting array of odd rows and even columns:")
newArray = sampleArray[::2, 1::2]
print(newArray)

Input Array:
[[  3   9   9  12]
 [ 16  18 231  24]
 [ 27  30  33  36]
 [ 39  42  45  58]
 [ 51  54  57  61]]

Printing array of odd rows and even columns:
[[ 9 12]
 [30 36]
 [54 61]]


### Exercise 8:
__Iterate both lists simultaneously__

Given a two Python list. Write a program to iterate both lists simultaneously and display items from list1 in original order and items from list2 in reverse order.

Tip: you can return a list in reverse with `[::-1]` (can you understand why?)

Expected output:

`10 400
20 300
30 200
40 100`

In [18]:
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]

In [19]:
for x, y in zip(list1, list2[::-1]):
    print(x, y)

10 400
20 300
30 200
40 100


### Exercise 9:
__Replace list’s item with new value if found__

You have given a Python list. Write a program to find value 20 in the list, and if it is present, replace it with 200. Only update the first occurrence of an item.

In [20]:
list1 = [5, 10, 15, 20, 25, 50, 20]

# your_code_here
# get the first occurrence index
index = list1.index(20)

# update item present at location
list1[index] = 200
print(list1)

[5, 10, 15, 200, 25, 50, 20]
